"""Regenerate data/do_not_apply.yaml from an Airtable table (weekly cron).

Some job seekers must avoid applying to certain companies for reasons that
change over time (an employer's active business relationships, conflicts of
interest). When that list lives in an Airtable, this script keeps
do_not_apply.yaml in sync with it instead of relying on a stale snapshot.

Env (in .env): AIRTABLE_TOKEN (PAT with data.records:read scoped to the
base), AIRTABLE_BASE_ID (app...), AIRTABLE_TABLE_ID (tbl...).

Config: data/do_not_apply_source.yaml in the data dir —
    name_field: Company            # column holding the company name
    stage_field: Status            # column holding the relationship stage
    stage_map:                     # stage value -> hold | caution | ok
      "Some Stage": hold
    extra:                         # manual entries preserved across syncs
      - {name: X, level: caution, why: direct competitor}

Names like "A / B" are split into separate entries; "(...)" suffixes are
stripped, so "PayPal / Venmo" blocks both and "NFCC (National...)" matches
"NFCC". Stages mapped to "ok" (or unmapped) are omitted entirely.

Run with --inspect to print the table's field names and distinct stage
values (for first-time setup). Exits 0 quietly when no token is configured,
so it is safe to leave in cron before setup.
"""
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
import os

import requests
import yaml

import config  # noqa: E402

SRC = config.DATA_DIR / "data" / "do_not_apply_source.yaml"
DEST = config.DATA_DIR / "data" / "do_not_apply.yaml"


def fetch_records(token, base, table):
    url = f"https://api.airtable.com/v0/{base}/{table}"
    headers = {"Authorization": f"Bearer {token}"}
    records, offset = [], None
    while True:
        params = {"offset": offset} if offset else {}
        r = requests.get(url, headers=headers, params=params, timeout=20)
        r.raise_for_status()
        data = r.json()
        records += data.get("records", [])
        offset = data.get("offset")
        if not offset:
            return records


def split_names(raw):
    """'PayPal / Venmo' -> ['PayPal', 'Venmo']; strip '(...)' suffixes."""
    out = []
    for part in str(raw).split("/"):
        name = re.sub(r"\s*\(.*?\)\s*", " ", part).strip()
        if name:
            out.append(name)
    return out


def main():
    token = os.environ.get("AIRTABLE_TOKEN")
    base = os.environ.get("AIRTABLE_BASE_ID")
    table = os.environ.get("AIRTABLE_TABLE_ID")
    if not (token and base and table):
        print("[sync] AIRTABLE_TOKEN/_BASE_ID/_TABLE_ID not configured; skipping.")
        return

    records = fetch_records(token, base, table)

    if "--inspect" in sys.argv:
        fields = sorted({k for r in records for k in r.get("fields", {})})
        print(f"{len(records)} records. Fields: {fields}")
        for f in fields:
            vals = sorted({str(r["fields"].get(f)) for r in records
                           if isinstance(r["fields"].get(f), str)})
            if 1 < len(vals) <= 25:
                print(f"  {f}: {vals}")
        return

    if not SRC.exists():
        sys.exit(f"[sync] {SRC} missing — run --inspect and write it (see docstring).")
    src = yaml.safe_load(SRC.read_text())
    name_f, stage_f = src["name_field"], src["stage_field"]
    stage_map = {k.strip().lower(): v for k, v in (src.get("stage_map") or {}).items()}

    entries, seen = [], set()
    for r in records:
        f = r.get("fields", {})
        raw_name, stage = f.get(name_f), str(f.get(stage_f, "")).strip()
        level = stage_map.get(stage.lower())
        if not raw_name or level in (None, "ok"):
            continue
        for name in split_names(raw_name):
            if name.lower() in seen:
                continue
            seen.add(name.lower())
            entries.append({"name": name, "level": level, "why": stage.lower()})

    for e in src.get("extra") or []:
        if e.get("name") and e["name"].lower() not in seen:
            seen.add(e["name"].lower())
            entries.append(e)

    entries.sort(key=lambda e: ({"hold": 0, "caution": 1}.get(e["level"], 2), e["name"]))
    header = (f"# GENERATED by scripts/sync_do_not_apply.py on {date.today().isoformat()}"
              " — do not hand-edit.\n"
              "# Manual additions belong in do_not_apply_source.yaml under 'extra'.\n")
    DEST.write_text(header + yaml.safe_dump(entries, sort_keys=False, allow_unicode=True))
    holds = sum(1 for e in entries if e["level"] == "hold")
    print(f"[sync] wrote {DEST.name}: {holds} hold, {len(entries) - holds} caution "
          f"(from {len(records)} records)")


if __name__ == "__main__":
    main()
